name: Primeiro workflow Linuxtips

on:
    workflow_dispatch

jobs:
    giropops:
        runs-on: ubuntu-26.04
        steps:
            - name: Confere versao ubuntu
              run: cat /etc/os-release

            - name: Exibir uma mensagem
              run: echo "Estou fazendo o curso de github actions da Linuxtips"
